name: swayzy
description: "Rewards for users with NFTs and coins for promoting brands and products on social media"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  go_router: ^14.8.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  firebase_ui_auth: ^1.16.1
  flutter_inappwebview: ^6.1.5
  google_sign_in: ^6.3.0
  firebase_ui_oauth_google: ^1.4.1
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.4.6
  settings_ui: ^2.0.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.0.0
  http: ^1.4.0
  solana: 0.31.2+1
  bip39: ^1.0.6
  intl: ^0.19.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300

  assets:
   - assets/images/
   - assets/images/badges_mocks/
   - assets/images/categories_mocks/
   - dotenv

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon/icon.png"

flutter_native_splash:
  color: "#4F17AA"
  color_dark: "#4F17AA"

  android_12:
    image: assets/images/icon_splash.png
    image_dark: assets/images/icon_splash.png